artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data: artifacts/data_ingestion/raw_data.csv
  target_column: Result

data_validation:
  root_dir: artifacts/data_validation
  raw_data: artifacts/data_ingestion/raw_data.csv
  train_data: artifacts/data_validation/train.csv
  test_data: artifacts/data_validation/test.csv

data_transformation:
  root_dir: artifacts/data_transformation
  train_data: artifacts/data_validation/train.csv
  test_data: artifacts/data_validation/test.csv  
  target_column: Result
  train_npy: artifacts/data_transformation/train.npy
  test_npy: artifacts/data_transformation/test.npy
  y_train: artifacts/data_transformation/y_train.csv
  y_test: artifacts/data_transformation/y_test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_npy: artifacts/data_transformation/train.npy
  test_npy: artifacts/data_transformation/test.npy
  model_name: artifacts/model_trainer/model.pkl